server:
  port: 10000
  bind_address: "0.0.0.0"
  secret_key: "changeme123"
  base_url: ""

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - json
  max_results: 10
  timeout: 1.0   # milliseconds speed target

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
  - name: bing
    engine: bing
    shortcut: bing
  - name: wikipedia
    engine: wikipedia
    shortcut: wiki
  - name: wikidata
    engine: wikidata
    shortcut: wd
  - name: open-meteo
    engine: open_meteo
    shortcut: weather
    categories: [weather]

ui:
  default_search: duckduckgo
  theme_args:
    results_on_new_tab: true
